apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    path: root-project
    repoURL: https://github.com/tuyentv96/argo-cd-example
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
