apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  type: LoadBalancer
  ports:
    - port: 5432 # Sets the port to run the postgres application
  selector:
    app: postgres
  loadBalancerIP: 192.168.1.125
