template: |
  {{- $app := .app }}
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: {{ $app.name }}
    namespace: argocd
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    project: default
    source:
      path: {{ $app.path }}
      repoURL: https://github.com/tuyentv96/pi-argo
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true

apps: []
