apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-http2-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - echo.picluster.xyz
    secretName: echo-http2-tls
  rules:
  - host: echo.picluster.xyz
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: echo-http2
              port:
                number: 80
