apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/echo-http

configMapGenerator:
- name: echo-http
  behavior: merge
  envs:
  - files/app.env

patches:
- path: deployment.yaml

images:
- name: nginx
  newName: mendhak/http-https-echo
  newTag: "24"
