apiVersion: v1
kind: Service # Create service
metadata:
  name: jaeger # Sets the service name
  labels:
    app: jaeger # Defines app to create service for
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 6831
      targetPort: 6831
      name: udp
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: tcp
  selector:
    app: jaeger
  loadBalancerIP: 192.168.1.204
