apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/hasty-challenge

configMapGenerator:
- name: job-api
  behavior: merge
  envs:
  - files/app.env

patches:
- path: deployment.yaml

images:
- name: nginx
  newName: tuyenuit/hasty-challenge
  newTag: "sha-25e8a36"
