apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: grafana-data # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: longhorn
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/grafana" # Sets the volume's path
