---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: echo-http-secret
spec:
  encryptedData:
    CF_API_TOKEN: AgCUzFasX4PJ9u1aDa6jY80jqfQUVLCvnMh79VrifR+QfZqan7uZkrkSdg+qjTndKX1N3Tqi5Td75yHwNPEvAJHno8XSDpEUcI05fRCk4zZ0Pqy7exjCQtb+CYUC/vIOfh1UuQmYs1VVemlNSmV32WL5lSxgPZPmsWbahBv+zUZ1PjzkGad8f4s9/7wG+riscdUFV2fTP58I/xoghzrGPGSX0hSn4iX1rAMQ2MaFwYcnwCRoDdZXmoR+i2wphvzsPx8qkjCpGXhXCHJk5YRuaXoqv7hLEeGlqCppXZiWXk4azKgFjdcvkUUyW+slXewoGl5hSloK1CekHjTun5VhuWGWWgAgc63hysComCrpehk/x6SCQ/L6+90SGsUJyKmtVNm7u2Urh7GKS8JoElZVwHCFJ46S55tECwPbhpCV4s0ylsBa9eSZVDptQO0Q3VKCHZ07P667zRKLeuEo81bWaGqmNnVihjb3f/NgPPo9MNjqp8ubJXvZ+kiwNGNM7jESC+W6saikp4JM+khXOZqOorH4MW3b2v7TgdlluDuUyFFNgBLtm8MvSwJp0Qtj+Q086vDL2cyYH0RLL+ahSSBLCd3/c7E1rkrIEr8q/cFb1vS20FLemJ6PiZlfvM/yLi894IhMGhRErseQoqPl7upzOJ7DA4tlTdTZaowKqT1CPSA8xUiQqAr0IBo61uUIOmh1/e6r7iCfbsUSV/1bCU394t8D1yd38GNwECzZcyjZXJs=
    FOO: AgBjf8NNHtrQr9IyzKEauN3ykgp4p7VygfjPBV2IB0fqzXXLxQF1okwyX6lY6exZBAcnzfYnoBT8Ie/Qcgw9X2CGEunI3Y3NRqoa6qgfOSxoxE9Uxr5Kh6NkGtwWN+EhRDycU9XpYktRE0l3/a2Bqq1vQipDt7OcQ4pFpbzT3PzP3Eg1x8VOzxbRR4DY/rhuvFebcmshpRlqbPMBdYs+R3lwtgaMczkuER9urABiW2XQFMS6eSalX4vCLRwOM+mfD12jXdOn648xiKsKr73gWT1sFrQhOobifBdecnhNU3r8/XNOk8xte2F4ob8Mw/6/BNS/XHto04PSIr+99QtLPFpxoIN6FLIm21XgkhTPm6vLPHI6FvL3/o8QjrTn1jUXhft9mkqllgWYI8LBlBHllmf9ivrY4YNshGM1NGtJ5bcAmfhNNkQEPEnMOwCM7pHOIFJdIFCKGhgBtHIbs/k3vKoZDPqzC1woM8p0HUZLig73tWv2P9MDWfHC1mK2Mdr57JY6Ya9UWXKaikXxU75ro8n03ewPooRiESfd40E90+ZqVN6Um0gBIes8QE34+GeETSSBbDgHXxOPktLIcV//pvml2L0Rzo2W/JHDXwyq0EAjdywfDTJbXfH9Uz2NaciKvVM1l223EoAZB/LDudPTHN0Q8zuWURMODJC7dTQo9oXOEAAYtuYQJl6amznJm7XfYfaiI+4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: echo-http-secret
---
