apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.5-alpine3.16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379  # Exposes container port
          args: ["--appendonly", "yes", "--requirepass", "mypassword"]
