apiVersion: v1
kind: Service # Create service
metadata:
  name: redis # Sets the service name
  labels:
    app: redis # Defines app to create service for
spec:
  type: LoadBalancer
  ports:
    - port: 6379 # Sets the port to run the postgres application
  selector:
    app: redis
  loadBalancerIP: 192.168.1.203
